name:                wordsGame
version:             0.1.0.0
github:              "salimp2009/wordsGame"
license:             BSD3
author:              "Salim Pamukcu"
maintainer:          "salimp2009@gmail.com"
copyright:           "BSD"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/salimp2009/wordsGame#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  wordsGame-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wordsGame

tests:
  wordsGame-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wordsGame
